#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# Functions
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#' Plot single gene across groups
#'
#' This function can be used for plotting a single gene expression across 
#' different groups in a study with complex group design. It uses the data
#' output from the DotPlot function in the Seurat package and uses ggplot2 
#' to re-create a dotplot for better visualization. In the output graph, y axis
#' is the cluster name and x axis is the group ID.
#'
#' @param seu_obj A complete Seurat object
#' @param feature Gene name. Only one gene is allowed.
#' @param splitby One of the column names in the meta.data slot of the Seurat object.
#' @return A ggplot object
#' @export
plot_singlegene_group<-function(
  seu_obj, 
  feature, 
  splitby 
  ){
  if (is.null(levels(seu_obj@meta.data[,splitby]))){
    seu_obj@meta.data[,splitby] <-factor(seu_obj@meta.data[,splitby], levels = names(table(seu_obj@meta.data[,splitby])))
  }
  dataplot<-DotPlot(seu_obj, features = feature, split.by =  splitby, cols = scales::hue_pal()(length((levels(seu_obj@meta.data[,splitby])))))
  dataplot<-dataplot$data
  dataplot$avg.exp<-scale(dataplot$avg.exp)
  dataplot$Cluster<-gsub("_[^_]*$", "", dataplot$id )
  dataplot$Disease<-gsub( ".*_", "", dataplot$id )
  dataplot$Disease<-factor(dataplot$Disease, levels = levels(seu_obj@meta.data[,splitby]))
  dataplot$Cluster<-factor(dataplot$Cluster, levels = levels(seu_obj))
  colnames(dataplot)[1:2]<-c('Avg.Exp', 'Pct.Exp')
  p<-ggplot(dataplot, aes(y = Cluster, x = Disease)) +  
    geom_tile(fill="white", color="white") +
    geom_point(aes( colour=Avg.Exp, size =Pct.Exp))  +  
    scale_color_gradientn(colours  =  colorRampPalette(c('grey80','lemonchiffon1','indianred1','darkred'))(255))+ 
    scale_size(range = c(0, 10))+
    theme(axis.line = element_blank(),
          axis.text.x = element_text(angle = 45, hjust = 1),
          plot.title = element_text(size = 16,hjust = 0.5, face = 'bold'),
          axis.text = element_text(size = 12),
          axis.title=element_text(size=8),
          legend.text=element_text(size=8),
          legend.title = element_text(size = 8),
          legend.position="right")+
    ylab("")+xlab("")+ggtitle(feature)
  p
}


#' Plot multiple genes across groups
#'
#' This function allows for visualization of multiple genes in multiple groups. 
#' It takes the single gene expression data generated by PlotSingleGeneGroup,
#' concatenate all data, and produces a dotplot graph where the group ID are in
#' x axis, wrapped by cell types, genes are on the y axis.
#'
#' @param seu_obj A complete Seurat object
#' @param features A vector of gene names.
#' @param splitby Group ID Must be one of the column names in the meta.data slot of the Seurat object.
#' @return A ggplot object
#' @export
plot_multigene_group<-function(
  seu_obj, 
  features, 
  splitby, 
  strip.color = NULL
  ){
 pb <- progress_bar$new(
   format = "  Ploting [:bar] :percent eta: :eta",
   clear = FALSE, total = length(features), width = 100)
 features=rev(features)
 plot_list<-list()
 for(i in 1:length(features)){
  pp<-invisible(
    plot_singlegene_group(seu_obj = seu_obj, feature = features[i], splitby = splitby)
  )
  plot_list[[i]]<-pp$data
  pb$tick()
  Sys.sleep(1 / length(features))
  }
  all_data<-do.call('rbind', plot_list)
  p <- invisible(
    ggplot(all_data, aes(x = Disease, y = features.plot)) +  
    geom_tile(fill="white", color="white") +
    geom_point(aes( colour=Avg.Exp, size =Pct.Exp), alpha=0.9)  +  
    scale_color_gradientn(colours  =  grDevices::colorRampPalette(c('grey80','lemonchiffon1','indianred1','darkred'))(255))+ 
    scale_size(range = c(0, 10))+
    theme(axis.line = element_blank(),
          axis.text.x = element_text(angle = 45, hjust = 1),
          plot.title = element_text(size = 16,hjust = 0.5, face = 'bold'),
          axis.text = element_text(size = 12),
          axis.title=element_text(size=8),
          legend.text=element_text(size=8),
          legend.title = element_text(size = 8),
          legend.position="right",
          strip.text = element_text(size = 14,colour = 'black',face = 'bold'))+
    ylab("")+xlab("")+ggtitle('')+
    facet_wrap(~Cluster, ncol = length(levels(seu_obj)))
  )
  g <- ggplot_gtable(ggplot_build(p))
  strip_both <- which(grepl('strip-t', g$layout$name))
  celltypes <-levels(seu_obj)
  fills <- strip.color
  if(is.null(strip.color)){
    fills<- scales::hue_pal()(length(celltypes))
  } 
  k <- 1
  for (i in strip_both) {
    j <- which(grepl('rect', g$grobs[[i]]$grobs[[1]]$childrenOrder))
    g$grobs[[i]]$grobs[[1]]$children[[j]]$gp$fill <- fills[k]
    k <- k+1
  }
  print(grid.draw(g))
}


